// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/markerpen.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// pca_pen_
List pca_pen_(MapMat S, IntegerVector gr, MapMat x0, double lambda, double gamma, double lr, int maxiter, int fan_maxinc, int fan_maxiter, double eps, int verbose);
RcppExport SEXP _markerpen_pca_pen_(SEXP SSEXP, SEXP grSEXP, SEXP x0SEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP lrSEXP, SEXP maxiterSEXP, SEXP fan_maxincSEXP, SEXP fan_maxiterSEXP, SEXP epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MapMat >::type S(SSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gr(grSEXP);
    Rcpp::traits::input_parameter< MapMat >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type fan_maxinc(fan_maxincSEXP);
    Rcpp::traits::input_parameter< int >::type fan_maxiter(fan_maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_pen_(S, gr, x0, lambda, gamma, lr, maxiter, fan_maxinc, fan_maxiter, eps, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_markerpen_pca_pen_", (DL_FUNC) &_markerpen_pca_pen_, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_markerpen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
