# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pca_pen_ <- function(S, gr, x0, lambda, gamma, lr, maxiter = 500L, fan_maxinc = 100L, fan_maxiter = 10L, eps = 1e-4, verbose = 0L) {
    .Call(`_markerpen_pca_pen_`, S, gr, x0, lambda, gamma, lr, maxiter, fan_maxinc, fan_maxiter, eps, verbose)
}

