# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pca_pen_ <- function(S, gr, x0, lambda, gamma, lr, maxiter = 500L, fan_maxinc = 100L, fan_maxiter = 10L, eps = 1e-4, verbose = 0L) {
    .Call(`_markerpen_pca_pen_`, S, gr, x0, lambda, gamma, lr, maxiter, fan_maxinc, fan_maxiter, eps, verbose)
}

#' Proximal operator on Fantope
#'
#' This function solves the optimization problem
#' \deqn{\min\quad-tr(AX) + \frac{1}{2\alpha}||X - B||_F^2}{min  -tr(AX) + (0.5 / \alpha) * ||X - B||_F^2}
#' \deqn{s.t.\quad X\in \mathcal{F}^d}{s.t. X in F^d}
#'
#' @param A       A symmetric matrix.
#' @param B       A symmetric matrix of the same dimension as \code{A}.
#' @param alpha   Proximal parameter.
#' @param d       Fantope parameter.
#' @param eps     Precision of the result.
#' @param inc     How many incremental eigenvalues to compute in each iteration.
#' @param maxiter Maximum number of iterations.
#' @param verbose Level of verbosity.
prox_fantope <- function(A, B, alpha, d, eps = 1e-5, inc = 1L, maxiter = 10L, verbose = 0L) {
    .Call(`_markerpen_prox_fantope`, A, B, alpha, d, eps, inc, maxiter, verbose)
}

